### ISSUE TITLE
Warning with JS Controler 3.0.7

### ISSUE THREAD

**Issue by Chaot1** [iobroker-community-adapters/ioBroker.wled#11]
After Update to JS Controler 3.0.7 i get a warning:
`wled.0	2020-04-13 09:57:17.397	warn	(25893) This value will not be set in future versions. Please report this to the developer.
wled.0	2020-04-13 09:57:17.397	warn	(25893) State value to set is invalid for wled.0.cc50e304f753.seg.0.col.0: The state is missing the required property val!
wled.0	2020-04-13 09:57:17.394	warn	(25893) This value will not be set in future versions. Please report this to the developer.
wled.0	2020-04-13 09:57:17.393	warn	(25893) State value to set is invalid for wled.0.cc50e304f753.seg.0.ix: The state is missing the required property val!`

JS Controler 3.0.7
NPM 6.14.4
NodeJS 12.16.2

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.wled/commit/97afa45ebb53e300392df833b759ae2ec16f7003#diff-7a9076d6d94e62c13d641aa71f19ae8eR738-R743

**Comment by DutchmanNL** [comment]
solved
