### ISSUE TITLE
Antwortzeit für Änderungen

### ISSUE THREAD

**Issue by nicedevil007** [iobroker-community-adapters/ioBroker.wled#122]
Hallo allerseits,

kurze Frage allgemein:

Normalerweise bin ich es gewohnt, dass Plugins die in ioBroker integriert werden "instant" nach einer Änderung auf einem Objekt reagieren und den neuen Status anzeigen. In dem Plugin hier hat man den 30 sec Timer der natürlich für sofortige Änderungen von irgendwelche Switches auf einem Dashboard ungeeignet ist.

Gibt es dafür ein Workaround? Den Timer auf 0 sec setzen ist denke nicht die Lösung da dann zu viele Abfragen gesendet werden an die kleinen Wemos.

**Comment by DutchmanNL** [comment]
Das ist leider der Nachteil von http pull, Version 0.6 wird komplett umgebaut auf Socket damit werden die Änderungen Instant übernommen.
Socket ist erst seit 1,5 Monaten in wled Firmware verfügbar daher konnte es vorher nur über pull Mechanismus

**Comment by nicedevil007** [comment]
Ahhhh perfekt, also nur eine Frage der Zeit, dann haben wir die Funktion! Super Sache!
