### ISSUE TITLE
DP nur schreiben bei Änderung

### ISSUE THREAD

**Issue by santa81** [iobroker-community-adapters/ioBroker.wled#13]
DP werden bei jedem Pull neu geschrieben und nicht bei jeder Änderung.
Führt zu erhöhtem Traffic usw,

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.wled/commit/97afa45ebb53e300392df833b759ae2ec16f7003#diff-7a9076d6d94e62c13d641aa71f19ae8eR702-R735
