### ISSUE TITLE
Error on first use after power reconnection

### ISSUE THREAD

**Issue by MC-1984** [iobroker-community-adapters/ioBroker.wled#17]
I am using an ESP32 with WLED 0.10. After disconnecting the ESP and LED strip from power and reconnecting it I cannot turn on the LED strip via the datapoints. I have to manually log in to the ESP and power it on manually once. After that I can instantly turn on and off the strip via the data points.

Adapter Version is 0.5.1
js-controller: 3.1.4

Edit: It only happens if I use the on data point under seg.0. If I use the on data point on the top level it works fine.

Detailled log:

`
wled.0 | 2020-05-22 19:45:43.716 | debug | (15524) Create_state called for : 246f28ae1b18.time with value : null
-- | -- | -- | --
wled.0 | 2020-05-22 19:45:43.715 | debug | (15524) Create_state called for : 246f28ae1b18.udpn.nn with value : null
wled.0 | 2020-05-22 19:45:43.715 | debug | (15524) Create_state called for : 246f28ae1b18.psave with value : null
wled.0 | 2020-05-22 19:45:43.714 | debug | (15524) Create_state called for : 246f28ae1b18.tt with value : null
wled.0 | 2020-05-22 19:45:43.713 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.rev with value : false
wled.0 | 2020-05-22 19:45:43.713 | debug | (15524) Object states created for channel seg with parameter : 0 : {"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":1
wled.0 | 2020-05-22 19:45:43.712 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.sel with value : true
wled.0 | 2020-05-22 19:45:43.711 | debug | (15524) Object states created for channel seg with parameter : 0 : {"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":1
wled.0 | 2020-05-22 19:45:43.644 | debug | (15524) Create special drop down state with value {"0":"Solid","1":"Blink","2":"Breathe","3":"Wipe","4":"Wipe Random","5":"Random Colors","6":"Sweep","7":"Dynamic","8":"Colorloop","9":"Rainbow","10":"
wled.0 | 2020-05-22 19:45:43.644 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.pal with value : 0
wled.0 | 2020-05-22 19:45:43.643 | debug | (15524) Object states created for channel seg with parameter : 0 : {"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":1
wled.0 | 2020-05-22 19:45:43.643 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.ix with value : 128
wled.0 | 2020-05-22 19:45:43.642 | debug | (15524) Object states created for channel seg with parameter : 0 : {"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":1
wled.0 | 2020-05-22 19:45:43.642 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.sx with value : 128
wled.0 | 2020-05-22 19:45:43.642 | debug | (15524) Object states created for channel seg with parameter : 0 : {"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":1
wled.0 | 2020-05-22 19:45:43.580 | debug | (15524) Create special drop donwn state with value {"0":"Solid","1":"Blink","2":"Breathe","3":"Wipe","4":"Wipe Random","5":"Random Colors","6":"Sweep","7":"Dynamic","8":"Colorloop","9":"Rainbow","10":
wled.0 | 2020-05-22 19:45:43.579 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.fx with value : 0
wled.0 | 2020-05-22 19:45:43.579 | debug | (15524) Object states created for channel seg with parameter : 0 : {"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":1
wled.0 | 2020-05-22 19:45:43.578 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.col.2_HEX with value : #000000
wled.0 | 2020-05-22 19:45:43.578 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.col.2 with value : 0,0,0
wled.0 | 2020-05-22 19:45:43.577 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.col.1_HEX with value : #000000
wled.0 | 2020-05-22 19:45:43.577 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.col.1 with value : 0,0,0
wled.0 | 2020-05-22 19:45:43.577 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.col.0_HEX with value : #ffa000
wled.0 | 2020-05-22 19:45:43.575 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.col.0 with value : 255,160,0
wled.0 | 2020-05-22 19:45:43.575 | debug | (15524) Naming : col with content : [255,160,0]
wled.0 | 2020-05-22 19:45:43.575 | debug | (15524) Object states created for channel seg with parameter : 0 : {"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":1
wled.0 | 2020-05-22 19:45:43.574 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.bri with value : 255
wled.0 | 2020-05-22 19:45:43.574 | debug | (15524) Object states created for channel seg with parameter : 0 : {"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":1
wled.0 | 2020-05-22 19:45:43.574 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.on with value : true
wled.0 | 2020-05-22 19:45:43.574 | debug | (15524) Object states created for channel seg with parameter : 0 : {"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":1
wled.0 | 2020-05-22 19:45:43.573 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.spc with value : 0
wled.0 | 2020-05-22 19:45:43.573 | debug | (15524) Object states created for channel seg with parameter : 0 : {"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":1
wled.0 | 2020-05-22 19:45:43.573 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.grp with value : 1
wled.0 | 2020-05-22 19:45:43.568 | debug | (15524) Object states created for channel seg with parameter : 0 : {"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":1
wled.0 | 2020-05-22 19:45:43.568 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.len with value : 300
wled.0 | 2020-05-22 19:45:43.568 | debug | (15524) Object states created for channel seg with parameter : 0 : {"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":1
wled.0 | 2020-05-22 19:45:43.567 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.stop with value : 300
wled.0 | 2020-05-22 19:45:43.567 | debug | (15524) Object states created for channel seg with parameter : 0 : {"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":1
wled.0 | 2020-05-22 19:45:43.566 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.start with value : 0
wled.0 | 2020-05-22 19:45:43.566 | debug | (15524) Object states created for channel seg with parameter : 0 : {"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":1
wled.0 | 2020-05-22 19:45:43.566 | debug | (15524) Create_state called for : 246f28ae1b18.seg.0.id with value : 0
wled.0 | 2020-05-22 19:45:43.565 | debug | (15524) Object states created for channel seg with parameter : 0 : {"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":1
wled.0 | 2020-05-22 19:45:43.545 | debug | (15524) Segment Array : [{"id":0,"start":0,"stop":300,"len":300,"grp":1,"spc":0,"on":true,"bri":255,"col":[[255,160,0],[0,0,0],[0,0,0]],"fx":0,"sx":128,"ix":128,"pal":0,"sel":true,"rev":false}]
wled.0 | 2020-05-22 19:45:43.544 | debug | (15524) Datatype : object
wled.0 | 2020-05-22 19:45:43.543 | debug | (15524) Create_state called for : 246f28ae1b18.mainseg with value : 0
wled.0 | 2020-05-22 19:45:43.543 | debug | (15524) Default state created : mainseg : 0
wled.0 | 2020-05-22 19:45:43.542 | debug | (15524) Datatype : number
wled.0 | 2020-05-22 19:45:43.542 | debug | (15524) Create_state called for : 246f28ae1b18.lor with value : 0
wled.0 | 2020-05-22 19:45:43.541 | debug | (15524) Default state created : lor : 0
wled.0 | 2020-05-22 19:45:43.540 | debug | (15524) Datatype : number
wled.0 | 2020-05-22 19:45:43.540 | debug | (15524) Create_state called for : 246f28ae1b18.udpn.recv with value : true
wled.0 | 2020-05-22 19:45:43.539 | debug | (15524) Object states created for channel udpn with parameter : recv : true
wled.0 | 2020-05-22 19:45:43.538 | debug | (15524) Create_state called for : 246f28ae1b18.udpn.send with value : false
wled.0 | 2020-05-22 19:45:43.537 | debug | (15524) Object states created for channel udpn with parameter : send : false
wled.0 | 2020-05-22 19:45:43.498 | debug | (15524) Datatype : object
wled.0 | 2020-05-22 19:45:43.498 | debug | (15524) Create_state called for : 246f28ae1b18.nl.tbri with value : 0
wled.0 | 2020-05-22 19:45:43.498 | debug | (15524) Object states created for channel nl with parameter : tbri : 0
wled.0 | 2020-05-22 19:45:43.497 | debug | (15524) Create_state called for : 246f28ae1b18.nl.fade with value : true
wled.0 | 2020-05-22 19:45:43.497 | debug | (15524) Object states created for channel nl with parameter : fade : true
wled.0 | 2020-05-22 19:45:43.495 | debug | (15524) Create_state called for : 246f28ae1b18.nl.dur with value : 60
wled.0 | 2020-05-22 19:45:43.495 | debug | (15524) Object states created for channel nl with parameter : dur : 60
wled.0 | 2020-05-22 19:45:43.494 | debug | (15524) Create_state called for : 246f28ae1b18.nl.on with value : false
wled.0 | 2020-05-22 19:45:43.494 | debug | (15524) Object states created for channel nl with parameter : on : false
wled.0 | 2020-05-22 19:45:43.441 | debug | (15524) Datatype : object
wled.0 | 2020-05-22 19:45:43.441 | debug | (15524) Create_state called for : 246f28ae1b18.ccnf.time with value : 12
wled.0 | 2020-05-22 19:45:43.441 | debug | (15524) Object states created for channel ccnf with parameter : time : 12
wled.0 | 2020-05-22 19:45:43.439 | debug | (15524) Create_state called for : 246f28ae1b18.ccnf.max with value : 5
wled.0 | 2020-05-22 19:45:43.439 | debug | (15524) Object states created for channel ccnf with parameter : max : 5
wled.0 | 2020-05-22 19:45:43.438 | debug | (15524) Create_state called for : 246f28ae1b18.ccnf.min with value : 1
wled.0 | 2020-05-22 19:45:43.438 | debug | (15524) Object states created for channel ccnf with parameter : min : 1
wled.0 | 2020-05-22 19:45:43.430 | debug | (15524) Datatype : object
wled.0 | 2020-05-22 19:45:43.430 | debug | (15524) Create_state called for : 246f28ae1b18.pl with value : -1
wled.0 | 2020-05-22 19:45:43.430 | debug | (15524) Default state created : pl : -1
wled.0 | 2020-05-22 19:45:43.430 | debug | (15524) Datatype : number
wled.0 | 2020-05-22 19:45:43.429 | debug | (15524) Create_state called for : 246f28ae1b18.pss with value : 7
wled.0 | 2020-05-22 19:45:43.429 | debug | (15524) Default state created : pss : 7
wled.0 | 2020-05-22 19:45:43.429 | debug | (15524) Datatype : number
wled.0 | 2020-05-22 19:45:43.429 | debug | (15524) Create_state called for : 246f28ae1b18.ps with value : -1
wled.0 | 2020-05-22 19:45:43.428 | debug | (15524) Default state created : ps : -1
wled.0 | 2020-05-22 19:45:43.428 | debug | (15524) Datatype : number
wled.0 | 2020-05-22 19:45:43.428 | debug | (15524) Create_state called for : 246f28ae1b18.transition with value : 7
wled.0 | 2020-05-22 19:45:43.427 | debug | (15524) Default state created : transition : 7
wled.0 | 2020-05-22 19:45:43.427 | debug | (15524) Datatype : number
wled.0 | 2020-05-22 19:45:43.426 | debug | (15524) Create_state called for : 246f28ae1b18.bri with value : 128
wled.0 | 2020-05-22 19:45:43.426 | debug | (15524) Default state created : bri : 128
wled.0 | 2020-05-22 19:45:43.426 | debug | (15524) Datatype : number
wled.0 | 2020-05-22 19:45:43.425 | debug | (15524) Create_state called for : 246f28ae1b18.on with value : false
wled.0 | 2020-05-22 19:45:43.425 | debug | (15524) Default state created : on : false
wled.0 | 2020-05-22 19:45:43.425 | debug | (15524) Datatype : boolean
wled.0 | 2020-05-22 19:45:43.424 | debug | (15524) Create_state called for : 246f28ae1b18._info.mac with value : 246f28ae1b18
wled.0 | 2020-05-22 19:45:43.424 | debug | (15524) State created : mac : "246f28ae1b18"
wled.0 | 2020-05-22 19:45:43.422 | debug | (15524) Datatype : string
wled.0 | 2020-05-22 19:45:43.422 | debug | (15524) Create_state called for : 246f28ae1b18._info.product with value : FOSS
wled.0 | 2020-05-22 19:45:43.421 | debug | (15524) State created : product : "FOSS"
wled.0 | 2020-05-22 19:45:43.412 | debug | (15524) Datatype : string
wled.0 | 2020-05-22 19:45:43.411 | debug | (15524) Create_state called for : 246f28ae1b18._info.brand with value : WLED
wled.0 | 2020-05-22 19:45:43.411 | debug | (15524) State created : brand : "WLED"
wled.0 | 2020-05-22 19:45:43.404 | debug | (15524) Datatype : string
wled.0 | 2020-05-22 19:45:43.404 | debug | (15524) Create_state called for : 246f28ae1b18._info.opt with value : 119
wled.0 | 2020-05-22 19:45:43.403 | debug | (15524) State created : opt : 119
wled.0 | 2020-05-22 19:45:43.402 | debug | (15524) Datatype : number
wled.0 | 2020-05-22 19:45:43.399 | debug | (15524) Create_state called for : 246f28ae1b18._info.uptime with value : 162
wled.0 | 2020-05-22 19:45:43.399 | debug | (15524) State created : uptime : 162
wled.0 | 2020-05-22 19:45:43.393 | debug | (15524) Datatype : number
wled.0 | 2020-05-22 19:45:43.393 | debug | (15524) Create_state called for : 246f28ae1b18._info.freeheap with value : 201408
wled.0 | 2020-05-22 19:45:43.393 | debug | (15524) State created : freeheap : 201408
wled.0 | 2020-05-22 19:45:43.388 | debug | (15524) Datatype : number
wled.0 | 2020-05-22 19:45:43.387 | debug | (15524) Create_state called for : 246f28ae1b18._info.lwip with value : 0
wled.0 | 2020-05-22 19:45:43.387 | debug | (15524) State created : lwip : 0
wled.0 | 2020-05-22 19:45:43.379 | debug | (15524) Datatype : number
wled.0 | 2020-05-22 19:45:43.379 | debug | (15524) Create_state called for : 246f28ae1b18._info.core with value : v3.2.3-14-gd3e562907
wled.0 | 2020-05-22 19:45:43.378 | debug | (15524) State created : core : "v3.2.3-14-gd3e562907"
wled.0 | 2020-05-22 19:45:43.359 | debug | (15524) Datatype : string
wled.0 | 2020-05-22 19:45:43.358 | debug | (15524) Create_state called for : 246f28ae1b18._info.arch with value : esp32
wled.0 | 2020-05-22 19:45:43.358 | debug | (15524) State created : arch : "esp32"
wled.0 | 2020-05-22 19:45:43.356 | debug | (15524) Datatype : string
wled.0 | 2020-05-22 19:45:43.355 | debug | (15524) Create_state called for : 246f28ae1b18._info.wifi.channel with value : 1
wled.0 | 2020-05-22 19:45:43.355 | debug | (15524) State created : channel : 1
wled.0 | 2020-05-22 19:45:43.355 | debug | (15524) Create_state called for : 246f28ae1b18._info.wifi.signal with value : 96
wled.0 | 2020-05-22 19:45:43.355 | debug | (15524) State created : signal : 96
wled.0 | 2020-05-22 19:45:43.354 | debug | (15524) Create_state called for : 246f28ae1b18._info.wifi.rssi with value : -52
wled.0 | 2020-05-22 19:45:43.354 | debug | (15524) State created : rssi : -52
wled.0 | 2020-05-22 19:45:43.353 | debug | (15524) Create_state called for : 246f28ae1b18._info.wifi.bssid with value : 76:83:C2:AA:14:1E
wled.0 | 2020-05-22 19:45:43.353 | debug | (15524) State created : bssid : "76:83:C2:AA:14:1E"
wled.0 | 2020-05-22 19:45:43.342 | debug | (15524) Datatype : object
wled.0 | 2020-05-22 19:45:43.341 | debug | (15524) Create_state called for : 246f28ae1b18._info.palcount with value : 52
wled.0 | 2020-05-22 19:45:43.341 | debug | (15524) State created : palcount : 52
wled.0 | 2020-05-22 19:45:43.338 | debug | (15524) Datatype : number
wled.0 | 2020-05-22 19:45:43.337 | debug | (15524) Create_state called for : 246f28ae1b18._info.fxcount with value : 103
wled.0 | 2020-05-22 19:45:43.337 | debug | (15524) State created : fxcount : 103
wled.0 | 2020-05-22 19:45:43.336 | debug | (15524) Datatype : number
wled.0 | 2020-05-22 19:45:43.335 | debug | (15524) Create_state called for : 246f28ae1b18._info.lip with value :
wled.0 | 2020-05-22 19:45:43.335 | debug | (15524) State created : lip : ""
wled.0 | 2020-05-22 19:45:43.321 | debug | (15524) Datatype : string
wled.0 | 2020-05-22 19:45:43.321 | debug | (15524) Create_state called for : 246f28ae1b18._info.lm with value :
wled.0 | 2020-05-22 19:45:43.320 | debug | (15524) State created : lm : ""
wled.0 | 2020-05-22 19:45:43.318 | debug | (15524) Datatype : string
wled.0 | 2020-05-22 19:45:43.318 | debug | (15524) Create_state called for : 246f28ae1b18._info.live with value : false
wled.0 | 2020-05-22 19:45:43.318 | debug | (15524) State created : live : false
wled.0 | 2020-05-22 19:45:43.302 | debug | (15524) Datatype : boolean
wled.0 | 2020-05-22 19:45:43.302 | debug | (15524) Create_state called for : 246f28ae1b18._info.udpport with value : 21324
wled.0 | 2020-05-22 19:45:43.301 | debug | (15524) State created : udpport : 21324
wled.0 | 2020-05-22 19:45:43.299 | debug | (15524) Datatype : number
wled.0 | 2020-05-22 19:45:43.298 | debug | (15524) Create_state called for : 246f28ae1b18._info.name with value : WLED
wled.0 | 2020-05-22 19:45:43.298 | debug | (15524) State created : name : "WLED"
wled.0 | 2020-05-22 19:45:43.259 | debug | (15524) Datatype : string
wled.0 | 2020-05-22 19:45:43.259 | debug | (15524) Create_state called for : 246f28ae1b18._info.str with value : false
wled.0 | 2020-05-22 19:45:43.258 | debug | (15524) State created : str : false
wled.0 | 2020-05-22 19:45:43.254 | debug | (15524) Datatype : boolean
wled.0 | 2020-05-22 19:45:43.254 | debug | (15524) Create_state called for : 246f28ae1b18._info.leds.seglock with value : false
wled.0 | 2020-05-22 19:45:43.253 | debug | (15524) State created : seglock : false
wled.0 | 2020-05-22 19:45:43.253 | debug | (15524) Create_state called for : 246f28ae1b18._info.leds.maxseg with value : 10
wled.0 | 2020-05-22 19:45:43.252 | debug | (15524) State created : maxseg : 10
wled.0 | 2020-05-22 19:45:43.251 | debug | (15524) Create_state called for : 246f28ae1b18._info.leds.maxpwr with value : 20000
wled.0 | 2020-05-22 19:45:43.251 | debug | (15524) State created : maxpwr : 20000
wled.0 | 2020-05-22 19:45:43.250 | debug | (15524) Create_state called for : 246f28ae1b18._info.leds.pwr with value : 400
wled.0 | 2020-05-22 19:45:43.250 | debug | (15524) State created : pwr : 400
wled.0 | 2020-05-22 19:45:43.249 | debug | (15524) Create_state called for : 246f28ae1b18._info.leds.pin with value : 2
wled.0 | 2020-05-22 19:45:43.249 | debug | (15524) State created : pin : [2]
wled.0 | 2020-05-22 19:45:43.249 | debug | (15524) Create_state called for : 246f28ae1b18._info.leds.wv with value : false
wled.0 | 2020-05-22 19:45:43.248 | debug | (15524) State created : wv : false
wled.0 | 2020-05-22 19:45:43.248 | debug | (15524) Create_state called for : 246f28ae1b18._info.leds.rgbw with value : false
wled.0 | 2020-05-22 19:45:43.248 | debug | (15524) State created : rgbw : false
wled.0 | 2020-05-22 19:45:43.247 | debug | (15524) Create_state called for : 246f28ae1b18._info.leds.count with value : 300
wled.0 | 2020-05-22 19:45:43.246 | debug | (15524) State created : count : 300
wled.0 | 2020-05-22 19:45:43.238 | debug | (15524) Datatype : object
wled.0 | 2020-05-22 19:45:43.237 | debug | (15524) Create_state called for : 246f28ae1b18._info.vid with value : 2005030
wled.0 | 2020-05-22 19:45:43.236 | debug | (15524) State created : vid : 2005030
wled.0 | 2020-05-22 19:45:43.228 | debug | (15524) Datatype : number
wled.0 | 2020-05-22 19:45:43.228 | debug | (15524) Create_state called for : 246f28ae1b18._info.ver with value : 0.10.0
wled.0 | 2020-05-22 19:45:43.227 | debug | (15524) State created : ver : "0.10.0"
wled.0 | 2020-05-22 19:45:43.225 | debug | (15524) Datatype : string
wled.0 | 2020-05-22 19:45:43.224 | debug | (15524) Expire time set for state : online with time in seconds : 20
wled.0 | 2020-05-22 19:45:43.223 | debug | (15524) Create_state called for : 246f28ae1b18._info._online with value : true
wled.0 | 2020-05-22 19:45:43.214 | debug | (15524) Data received from WLED device {"state":{"on":false,"bri":128,"transition":7,"ps":-1,"pss":7,"pl":-1,"ccnf":{"min":1,"max":5,"time":12},"nl":{"on":false,"dur":60,"fade":true,"tbri":0},"udpn":{
wled.0 | 2020-05-22 19:45:43.214 | debug | (15524) "API response data : [object Object]"
wled.0 | 2020-05-22 19:45:43.158 | debug | (15524) GET API called for : http://192.168.50.215/json
wled.0 | 2020-05-22 19:45:43.157 | debug | (15524) Read data called : "192.168.50.215"
wled.0 | 2020-05-22 19:45:43.007 | debug | (15524) API feedback{"success":true}
wled.0 | 2020-05-22 19:45:42.871 | debug | (15524) Post API called for : http://192.168.50.215/json and values : {"seg":{"id":0,"on":true}}
wled.0 | 2020-05-22 19:45:42.865 | debug | (15524) Prepare API call for device : 246f28ae1b18 and values + [object Object]
wled.0 | 2020-05-22 19:45:42.865 | debug | (15524) values segment {"seg":{"id":0,"on":true}}
wled.0 | 2020-05-22 19:45:42.865 | debug | (15524) test number : 0
wled.0 | 2020-05-22 19:45:42.864 | debug | (15524) Send seg
wled.0 | 2020-05-22 19:45:42.863 | debug | (15524) state wled.0.246f28ae1b18.seg.0.on changed: true (ack = false)
`

**Comment by DutchmanNL** [comment]
please test with version 0.5.2

**Comment by MC-1984** [comment]
Version 0.5.2 does not work at all. The instance stays completely red:
<img width="230" alt="image" src="https://user-images.githubusercontent.com/58948938/91935022-06942d80-eced-11ea-9bba-ae56bf623938.png">


wled.0 | 2020-09-02 07:20:26.537 | error | at Wled.onReady (/opt/iobroker/node_modules/iobroker.wled/main.js:49:3)
-- | -- | -- | --
wled.0 | 2020-09-02 07:20:26.537 | error | at processTicksAndRejections (internal/process/task_queues.js:93:5)
wled.0 | 2020-09-02 07:20:26.537 | error | at Wled.tryKnownDevices (/opt/iobroker/node_modules/iobroker.wled/main.js:638:30)
wled.0 | 2020-09-02 07:20:26.537 | error | (2940) TypeError: this.readData is not a function
wled.0 | 2020-09-02 07:20:26.532 | error | (2940) unhandled promise rejection: this.readData is not a function
Unhandled | 2020-09-02 07:20:26.531 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by DutchmanNL** [comment]
@MC-1984 thank you,  made a stupid type fixed in 0.5.4 and removed 0.5.3 from NPM to avoid more issues for other users

**Comment by MC-1984** [comment]
Sorry for the late reply: Works perfectly! Thanks!
