### ISSUE TITLE
missing Attributes with WLED 0.10.0

### ISSUE THREAD

**Issue by volkerrichert** [iobroker-community-adapters/ioBroker.wled#19]
**Describe the bug**  
3 attributes are missing 
wled.0 | 2020-07-19 19:08:59.081 | warn | (15662) State attribute definition missing for + lor
wled.0 | 2020-07-19 19:08:58.914 | warn | (15662) State attribute definition missing for + lip
wled.0 | 2020-07-19 19:08:58.906 | warn | (15662) State attribute definition missing for + lm

**To Reproduce**  
Update yout wled to 0.10.0

**Expected behavior**

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.wled/commit/f0c22ebabff53c48c707b210a6c35e94b968bec3
