### ISSUE TITLE
Funktionsvorschlag

### ISSUE THREAD

**Issue by LiveSide** [iobroker-community-adapters/ioBroker.wled#2]
Wenn der on (On/Off) Status auf false gesetzt wird gehen ja, wie gewünscht die LEDs aus.
Wenn nun etwas geändert wird wie Farbe oder ähnliches, bleiben diese weiterhin aus.
ist es möglich, den on/off status, dann nur für das geänderte Segment einzuschalten?
die anderen Segmente bleiben weiterhin abgeschalten

**Comment by DutchmanNL** [comment]
> ist es möglich, den on/off status, dann nur für das geänderte Segment einzuschalten?
> die anderen Segmente bleiben weiterhin abgeschalten

Dafür muss WLED mir in der api eine state Bereitstellen womit ich nur Einsegment an/aus schalten kan.
Der jetzige on/off ist fuer dein gesammten streifen.

Erstelle bitte dort ein issue, dan diskutieren ich das mit Aircookie :)

**Comment by DutchmanNL** [comment]
@LiveSide hattest du ei WLED nachgefragt ?

**Comment by LiveSide** [comment]
nein habe ich nicht... 
habe ich vergessen...

**Comment by DutchmanNL** [comment]
Pending : https://github.com/Aircoookie/WLED/issues/511

**Comment by DutchmanNL** [comment]
implemented
