### ISSUE TITLE
wLED speichert keine Segmente.

### ISSUE THREAD

**Issue by LiveSide** [iobroker-community-adapters/ioBroker.wled#3]
wLED löscht alle angelegten Segmente wenn man den Strom wegnimmt.
ist es möglich das der Adapter die Segmente wieder schreibt, nachdem dieser vom Strom getrennt war?

**Comment by DutchmanNL** [comment]
Jup geht, WLED hat die Möglichkeit jetzige Einstellung als "preset" zu speichern, preset 16 unterstützt auch Segmente.

Der adapter hat einen Datenpunkt "psave" (Save current light config to specified preset slot).
- Stelle mal deine Lampen ein und gebe dort 16 ein
- nimm WLED vom Strom und starte neu.
- Wähle jetzt einen Favoriten (16)
- du kannst in den Einstellungen automatisch preset 16 bei starten laden

Damit sollte du erreichen können was du möchtest, berichte bitte ob es klappt.

**Comment by DutchmanNL** [comment]
ich gehe mal davon aus das es geklappt hat ?
