### ISSUE TITLE
Liste der Effekte in dem Datenpunkt anlegen 

### ISSUE THREAD

**Issue by xXBJXx** [iobroker-community-adapters/ioBroker.wled#4]
Ein Dropdown-Liste in den fx datenpunkt anlegen damit man die Effekte auswählen kann 
![Screenshot_11](https://user-images.githubusercontent.com/32600934/74074107-11176e80-4a0d-11ea-9e51-3c332eed883b.png)

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.wled/commit/69f9f3e4f8c78cc11e1352bef8c9a0e6db5fec23#diff-7a9076d6d94e62c13d641aa71f19ae8eR206-R512
