### ISSUE TITLE
On/Off Status 

### ISSUE THREAD

**Issue by eddy-ch** [iobroker-community-adapters/ioBroker.wled#40]
Hallo,

bei mir wir seit v.0.5.1 der Status On/Off nur einmalig auf true gesetzt, danach wird nicht mehr aktualisiert.
Ist das so gewollt?

**Comment by DutchmanNL** [comment]
Hi, welche WLED Firmware Version ?

**Comment by eddy-ch** [comment]
habe aktuell die 10.2 am laufen, mit 6 x esp32.
das Problem hatte ich auch mit früheren Versionen, deshalb bin ich bei 0.5 geblieben.

**Comment by DutchmanNL** [comment]
Danke, schaue es mir an

**Comment by watho** [comment]
Ich habe das Problem auch mit Firmware 0.11.0. Ich habe mal in die json-api geschaut. Der on-Datenpunkt in state wird von WLED korrekt auf true/false gesetzt. Der on-Wert in den einzelnen Segmenten bleibt aber auf true. Vielleicht hilft dir das ja weiter.

**Comment by watho** [comment]
Ich denke, ich habe das Problem behoben. Wer will, kann die korrigierte Version von hier installieren: https://github.com/watho/ioBroker.wled

**Comment by eddy-ch** [comment]
Hi Watho, funktioniert...
vielen Dank
