### ISSUE TITLE
Object / String Problem

### ISSUE THREAD

**Issue by FalkPe** [iobroker-community-adapters/ioBroker.wled#43]
Hallo Raffi,
Hier ein kleines Problem mit einem State bei mir. In Aden Bildern siehst du es. 

![IMG_20200904_202017](https://user-images.githubusercontent.com/60939758/92298723-312ff180-ef4c-11ea-98f0-5e59ead65267.jpg)
![IMG_20200904_201905](https://user-images.githubusercontent.com/60939758/92298725-32611e80-ef4c-11ea-86a7-c3e61513b391.jpg)
![IMG_20200904_201941](https://user-images.githubusercontent.com/60939758/92298726-32f9b500-ef4c-11ea-94b4-66647d18c63a.jpg)

**Comment by FalkPe** [comment]
Downgrade to Adapter Version 0.5.0 solved it

**Comment by DutchmanNL** [comment]
Funny nothing changed for that between the version but thank you looking at it helps me figuring it out. Hope this or next week to spend time in this adapter

**Comment by FalkPe** [comment]
Fehler ist still da

**Comment by FalkPe** [comment]
Also, ich bin nochmal auf 0.5.0 runter, habe die Datenpunkte vom entsprechenden WLED gelöscht und neu anlegen lassen, scheint erstmal ohne Fehler zu funktionieren.

**Comment by foxriver76** [comment]
Naja, das Problem ist dass du hier 
https://github.com/iobroker-community-adapters/ioBroker.wled/blob/b8616c6860a5ced6cb9bf220f733f8e400d71152/main.js#L703

`typeof value` machst, wenn der value jetzt aktuell ein Objekt ist, in dem Fall wohl ein Array, weißt du den Typ `object` zu, das gefällt dem Controller dann nicht wenn der User ein String reinsetzt. Aber auch so wenn es ein array ist, muss der Typ für den Controller `array` sein und nicht ein Objekt. Kannst du mit `Array.isArray(value) ? 'array' : typeof value` z. B. handhaben. Allerdings schätze ich dass es eher ein String sein sollte.

**Comment by DutchmanNL** [comment]
duplicate https://github.com/iobroker-community-adapters/ioBroker.wled/issues/52
