### ISSUE TITLE
pl & fx are not synced (correctly)

### ISSUE THREAD

**Issue by volkerrichert** [iobroker-community-adapters/ioBroker.wled#47]
- When changing "Preset Cycle" (pl = 0 / -1) in web frontend the value will not be changed in ioBroker
- fx will not set to "Solid" (0). Other Effects work fine

Changing both in ioBroker works fine and will be set in WLED

**Versions:**  
 - Adapter version: v0.5.4
 - JS-Controller version: v3.1.6
 - Node version: v12.18.3
 - Operating system: linux / docker

**Comment by watho** [comment]
I think i fixed this issue while fixing #40 . You could install the fixed version from https://github.com/watho/ioBroker.wled

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.wled/commit/8dd5aa1a2315a4e6fa86c7c4aa4104208be96019
