### ISSUE TITLE
Nach Update auf 0.5.4 -> WARN Meldungen bei Verwendung von Strings

### ISSUE THREAD

**Issue by Flyor** [iobroker-community-adapters/ioBroker.wled#52]
**Description**  
Ich schreibe mittels Blockly die aktuelle Farbe (Primary Color RGB) in einen Datenpunkt.
Ändere die primary Color RGB manuell per Blockly auf eine andere Farbe (0,0,255)
Nach einer Zeit, überschreibe ich den Datenpunkt mit Primary Color RGB erneut mit der in der Variable gespeicherten Farbe. 

Seit dem letzten Update, entstehen hierbei sämtliche Fehlermeldungen im Log. Die Funktion ist jedoch nicht beeinträchtigt. 

**Versions:**  
 - Adapter version: 0.5.4
 - JS-Controller version: 3.1.6
 - Node version: 10.22.0
 - Operating system: Ubuntu 20.04 LTS

![image](https://user-images.githubusercontent.com/64526892/93307577-6d433c00-f801-11ea-8164-c820911f49d9.png)

![image](https://user-images.githubusercontent.com/64526892/93307628-7df3b200-f801-11ea-9969-ed8b93ad968d.png)

![image](https://user-images.githubusercontent.com/64526892/93307664-8946dd80-f801-11ea-9b9d-94c6ce042c4d.png)

**Comment by Flyor** [comment]
The rework (screenshot below) of the script doesn't change anything.
![image](https://user-images.githubusercontent.com/64526892/93334509-57477280-f825-11ea-9397-8f3c014ece37.png)

 Perhaps, the problem isn't about the choice of the manual color selection. I think the problem is the action that I want to "cache" the actual color at a variable. If you look at the log, javascript returned the error that the state "Buero_LED_Farbe" expects an object, instead of an array. If I changed the state to an object, it won't work. The log shows: that I send a string instead of an object. 

That's why I tried it with a blockly variable instead of my own state:

![image](https://user-images.githubusercontent.com/64526892/93336309-e2c20300-f827-11ea-99e2-befe5684bdf6.png)

The result is nearly the same - the functionality is fine, but the log shows this:

![image](https://user-images.githubusercontent.com/64526892/93336390-fec5a480-f827-11ea-9af5-57a02e0cb915.png)

at least: 1 warning less than before.

**Comment by Flyor** [comment]
If it would be possible to create a datapoint at the adapter "last color" or "color history", there would be no need to work with own variables.

**Comment by DutchmanNL** [comment]
> If it would be possible to create a datapoint at the adapter "last color" or "color history", there would be no need to work with own variables.

please feel free to create a separated issue for that, its possible to implement :) in this issue I will ensure the object part

**Comment by Flyor** [comment]
Is there any other content you need to fix it? I  started the enhancement of my idea.

**Comment by DutchmanNL** [comment]
For this Moment only time to ha dale it, I have my children this week so more time next week hope to be able to Adresse it than

**Comment by Chaot1** [comment]
I have exactly the same Problem.
I try to change the Colors with a Blockly Script. After every Resart i get the Message that i Assign a String to a Object.
When i change the Datapoint manually to "gemischt" it works perfect 

`

javascript.0 | 2020-09-24 22:30:21.084 | warn | (425) at processImmediate (internal/timers.js:456:21)
-- | -- | -- | --
javascript.0 | 2020-09-24 22:30:21.083 | warn | (425) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5384:37)
javascript.0 | 2020-09-24 22:30:21.083 | warn | (425) at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:472:25)
javascript.0 | 2020-09-24 22:30:21.083 | warn | (425) at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1055:38)
javascript.0 | 2020-09-24 22:30:21.083 | warn | (425) at Object.<anonymous> (script.js.Systeminfo.WLED_Thermo1:66:5)
javascript.0 | 2020-09-24 22:30:21.082 | warn | (425) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1358:20)
javascript.0 | 2020-09-24 22:30:21.080 | warn | (425) You are assigning a string to the state "wled.0.cc50e304f753.seg.0.col.0" which expects a object. Please fix your code to use a object or change the state type to string. This warning might bec

`

Maybe its possible to change the State within the Adapter?

**Comment by Flyor** [comment]
> I have exactly the same Problem.
> I try to change the Colors with a Blockly Script. After every Resart i get the Message that i Assign a String to a Object.
> When i change the Datapoint manually to "gemischt" it works perfect
> 
> `
> 
> javascript.0	2020-09-24 22:30:21.084	warn	(425) at processImmediate (internal/timers.js:456:21)
> javascript.0	2020-09-24 22:30:21.083	warn	(425) at Immediate._onImmediate (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5384:37)
> javascript.0	2020-09-24 22:30:21.083	warn	(425) at Object.stateChange (/opt/iobroker/node_modules/iobroker.javascript/main.js:472:25)
> javascript.0	2020-09-24 22:30:21.083	warn	(425) at Object.callback (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1055:38)
> javascript.0	2020-09-24 22:30:21.083	warn	(425) at Object. (script.js.Systeminfo.WLED_Thermo1:66:5)
> javascript.0	2020-09-24 22:30:21.082	warn	(425) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1358:20)
> javascript.0	2020-09-24 22:30:21.080	warn	(425) You are assigning a string to the state "wled.0.cc50e304f753.seg.0.col.0" which expects a object. Please fix your code to use a object or change the state type to string. This warning might bec
> `
> 
> Maybe its possible to change the State within the Adapter?

Which data Point u changed manualy? The one who cache the color, or the one at the adapter?

**Comment by Chaot1** [comment]
I change the datapoint  "....seg.0.col.0" (pen on the right side) manually to String (or Mixed).

**Comment by Flyor** [comment]
> I change the datapoint "....seg.0.col.0" (pen on the right side) manually to String (or Mixed).

I tried it too and it works for me also. Nice - Thanks a lot! Since now, i tried to change the datapoint of my "cache". But this is the best solution. Switiching the datapoint from "object" to "mixed". 

@DutchmanNL Please use this solution - will be the easiest way i think.

**Comment by DutchmanNL** [comment]
No that’s just a hack ;)

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.wled/commit/f8e7e2b8f04f2f77e43fe29cc8455429aa82404f
