### ISSUE TITLE
RAM verbrauch hoch

### ISSUE THREAD

**Issue by LiveSide** [iobroker-community-adapters/ioBroker.wled#6]
Hallo 
der RAM verbrauch war bei mir knapp bei 400MB und nach dem neustart des adapters auf 50MB
evtl sollte dieses Problem behoben werden.

grüße :D

**Comment by DutchmanNL** [comment]
sollte behoben sein, de bonjour (netzwerk scan) alle 30 Sekunden zu starten ohne ihn zu beenden ist nicht so ne gute idee :)

https://github.com/iobroker-community-adapters/ioBroker.wled/commit/fb36423b721525f7db06d4f6cb72c6b9eb6a8d43
