### ISSUE TITLE
Do not query '/json' in timer to update states

### ISSUE THREAD

**Issue by volkerrichert** [iobroker-community-adapters/ioBroker.wled#8]
You query /json in every round trip. This costs a lot of heap (on my esp8266) which causes a forced WLAN disconnect. I have a lot of WLAN issues with my first WLED controller.

I set up a test ESP and got this DEBUG log

```
---DEBUG INFO---
Runtime: 25040896
Unix time: 1585766772
Free heap: 6880
Wifi state: 3
State time: 24710446
NTP last sync: 6010
Client IP: 192.168.120.48
Loops/sec: 2430
Heap too low! 6880
Forcing reconnect.
Access point disabled.
Connecting to IoT...

Connected! IP address: 192.168.120.48
Init STA interfaces
mDNS started
Disconnected!
Access point disabled.
Connecting to IoT...

Connected! IP address: 192.168.120.48
Init STA interfaces
mDNS started
...
```

A heap below 9k will cause a WLAN forced reconnect

```c++
    if (heap < 9000 && lastHeap < 9000) {
      DEBUG_PRINT("Heap too low! ");
      DEBUG_PRINTLN(heap);
      forceReconnect = true;
    }
```

**To Reproduce**  
Try to load /json form your WLED serveral time by browser. At some point the ESP not response anymore and will disconnect itselfs from WLAN.

But you doesn't need to request the whole JSON. You can request every part using `/json/state`, `/json/info`, `/json/effects` and `/json/palettes`. State could be requested every round trip. The rest could be requeste at startup only or e.g. every 5 minutes.

I don't know if this is the root cause of my ESP being unreachable after a while. I'll disable 

Volker

**Comment by volkerrichert** [comment]
se PR #9

**Comment by DutchmanNL** [comment]
thank you, I will take a look at it but looks a lit to much code change for this small behavior.
we can simply already move the pallet and effects out but just one call and than comparing it with the values in memory it !value make a call otherwise not

I will relook at the code setup to define the most efficient way and fitting in current logic

**Comment by volkerrichert** [comment]
I just spilt yout readData into subFunctions

**Comment by volkerrichert** [comment]
ok, and changed the result "success"/"failed". The rest is some spaces removed by the IDE

**Comment by DutchmanNL** [comment]
have to look carefully and not just a second on it will do this evening :)

**Comment by volkerrichert** [comment]
any update?

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.wled/commit/7a5cd533629421afb77ccc4069594b6915c23d32
