### ISSUE TITLE
Frage: WLED mit iot-Adapter

### ISSUE THREAD

**Issue by guergen1** [iobroker-community-adapters/ioBroker.wled#85]
Warum kann man im iot-Adapter keinen Befehl für Alexa anlegen?
![grafik](https://user-images.githubusercontent.com/34395245/98283388-ebb99000-1f9f-11eb-8764-3de42855880b.png)
![grafik](https://user-images.githubusercontent.com/34395245/98283441-fb38d900-1f9f-11eb-9bbf-d235d56da449.png)
![grafik](https://user-images.githubusercontent.com/34395245/98283658-42bf6500-1fa0-11eb-9afe-abd67b350d65.png)

**Comment by raspilc** [comment]
Gleiches Problem bei mir.Kann man aber etwas kryptisch lösen mit nem kleinen workaround:
Wenn man den Datenpunkt das erste mal im iot-Adapter verknüpfen will, kommt die besagte Meldung. Wenn man danach in den betreffenden Datenpunkt schaut,  wurde ein Smart-Name mit dem Namen des Datenpunktes angelegt.Diesen löschen und dann den DP wieder im iot-Adapter hinzufügen.Dann wird der akzeptiert.Stellt sich nur die Frage, ob das ein Problem im WLED-Adapter oder im iot-Adapter ist. Vielleicht hilft diese Info ja irgendwie.

**Comment by DutchmanNL** [comment]
iot adapter benoetigt daten in einer gewissen Struktur, diese kan man als device anlegen als workarround.

ich schaue mir mal ich das feste einbauen kann

<img width="982" alt="Schermafbeelding 2020-11-18 om 22 07 34" src="https://user-images.githubusercontent.com/7318445/99588180-78297100-29ea-11eb-9d2c-ed65ab5796d7.png">
