### ISSUE TITLE
please update for support v0.11.0 "Mirai"

### ISSUE THREAD

**Issue by morphygee** [iobroker-community-adapters/ioBroker.wled#94]
please update for support v0.11.0 "Mirai"

controlling this version is possible now, but it doeas not read the states. especially on/off, colors, effects

**Comment by DutchmanNL** [comment]
https://github.com/iobroker-community-adapters/ioBroker.wled/commit/27df97dcfb65e9024c09e5ed84354af697bbb209

new. version will be released soon
