### ISSUE TITLE
Datapoint for birghtness in percent and effect ID without desciption

### ISSUE THREAD

**Issue by baeriwiliwonka** [iobroker-community-adapters/ioBroker.wled#99]
Would be nice to have a datapoint in the segments to control the brightness in percent.
This will allow to ise the datapoint directly in Google Assistant.

Using the current value for the brightness in Google Assistant only allows the user to tune from 0-100 instead of 0-255.

I have a workaround with a small blockly which calculates the decimal value out of the percentage value and vice versa, but it would be much more comfortable to have it directly out of the adapter.

It also would be nice to control the effect ID directly with a number, to enable Google Assistant to say something like "turn on effect 2". At the moment it is not possible to change the effect by a single number, just by the dropdown.

Thanks!

**Comment by DutchmanNL** [comment]
> Using the current value for the brightness in Google Assistant only allows the user to tune from 0-100 instead of 0-255.

this can be achieved by using an alias with conversion as we want to keep 255 at the datapoints for more detailed. calibration
